### ISSUE TITLE
Issue with acct_number

### ISSUE THREAD

**Issue by illectronic** [deep-security/aws-security-hub#5]
acct _number is undefined so if you set a global var to your account number this works. Otherwise it doesn't work. A better way would be to pull it from IAM commands.

**Comment by illectronic** [comment]
still does not work.

16:53:08
Boto Version = 1.9.93

16:53:08
START RequestId: b5d37dfa-b6c2-48dc-b656-60b515de2110 Version: $LATEST

16:53:08
local variable 'total_events' referenced before assignment: UnboundLocalError Traceback (most recent call last): File "/var/task/lambda_function.py", line 384, in lambda_handler 'total_events': total_events, UnboundLocalError: local variable 'total_events' referenced before assignment

16:53:08
END RequestId: b5d37dfa-b6c2-48dc-b656-60b515de2110

16:53:08
REPORT RequestId: b5d37dfa-b6c2-48dc-b656-60b515de2110	Duration: 0.90 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 34 MB

17:03:08
START RequestId: 39305c6a-a1f8-453c-90a5-d27ceac6262f Version: $LATEST

17:03:08
Amazon SNS message received

17:03:08
Extracted Deep Security event(s) from the SNS message

17:03:08
Found 5 Deep Security events...processing

17:03:08
Security event does not meet the criteria to send to AWS Security Hub

17:03:08
Security event does not meet the criteria to send to AWS Security Hub

17:03:08
Security event does not meet the criteria to send to AWS Security Hub

17:03:08
Security event does not meet the criteria to send to AWS Security Hub

17:03:08
Security event does not meet the criteria to send to AWS Security Hub

17:03:08
END RequestId: 39305c6a-a1f8-453c-90a5-d27ceac6262f

17:03:08
REPORT RequestId: 39305c6a-a1f8-453c-90a5-d27ceac6262f	Duration: 21.17 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 35 MB

17:06:08
START RequestId: e79cb638-39e5-420a-9869-c59e148e4d28 Version: $LATEST

17:06:08
Amazon SNS message received

17:06:08
Extracted Deep Security event(s) from the SNS message

17:06:08
Found 1 Deep Security events...processing

17:06:08
Security event does not meet the criteria to send to AWS Security Hub

17:06:08
END RequestId: e79cb638-39e5-420a-9869-c59e148e4d28

17:06:08
REPORT RequestId: e79cb638-39e5-420a-9869-c59e148e4d28	Duration: 14.87 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 35 MB

17:06:08
START RequestId: e48c8604-c92a-4c38-bc43-28ec3a37641d Version: $LATEST

17:06:08
Amazon SNS message received

17:06:08
Extracted Deep Security event(s) from the SNS message

17:06:08
Found 1 Deep Security events...processing

17:06:08
Security event does not meet the criteria to send to AWS Security Hub

17:06:08
END RequestId: e48c8604-c92a-4c38-bc43-28ec3a37641d

17:06:08
REPORT RequestId: e48c8604-c92a-4c38-bc43-28ec3a37641d	Duration: 0.55 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 35 MB

17:09:21
START RequestId: 9a02e65f-f5e4-47c8-b6db-81d82f0f04a0 Version: $LATEST

17:09:21
local variable 'total_events' referenced before assignment: UnboundLocalError Traceback (most recent call last): File "/var/task/lambda_function.py", line 384, in lambda_handler 'total_events': total_events, UnboundLocalError: local variable 'total_events' referenced before assignment

17:09:21
END RequestId: 9a02e65f-f5e4-47c8-b6db-81d82f0f04a0

17:09:21
REPORT RequestId: 9a02e65f-f5e4-47c8-b6db-81d82f0f04a0	Duration: 5.77 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 35 MB

17:09:31
START RequestId: 115a3ba5-cb65-4d73-8808-33c5020e0498 Version: $LATEST

17:09:31
local variable 'total_events' referenced before assignment: UnboundLocalError Traceback (most recent call last): File "/var/task/lambda_function.py", line 384, in lambda_handler 'total_events': total_events, UnboundLocalError: local variable 'total_events' referenced before assignment

17:09:31
END RequestId: 115a3ba5-cb65-4d73-8808-33c5020e0498

17:09:31
REPORT RequestId: 115a3ba5-cb65-4d73-8808-33c5020e0498	Duration: 0.65 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 35 MB
